# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16670bb7d59f2113dca178de8582554f9d55a52854d369f5733f70ddee76db636173859c218e1edf46e50068e0f268f04a95f11d9782cbf167aea95a4644f4b1

test:
  secret_key_base: 0cd0c055c1fe5d850d7a0c3b19eb156af8ea4791d364702e01f43563408f661c61078da3fc48d4b03442ae77caa7301f0aa98d13528d339e7807bda1af5b8c22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
